# Generated by Django 5.0.6 on 2024-06-19 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(max_length=50)),
                ('detail_value', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='content.content')),
            ],
        ),
    ]
