# Generated by Django 5.0.6 on 2024-06-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentDetail',
        ),
    ]
