# Generated by Django 5.0.6 on 2024-06-21 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_contentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='audio_content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='pdf_content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='word_content',
        ),
        migrations.CreateModel(
            name='ContentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_content', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('pdf_content', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('word_content', models.FileField(blank=True, null=True, upload_to='words/')),
                ('audio_content', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='content.content')),
            ],
        ),
    ]
